### ISSUE TITLE
This code is actually a Martingale betting system

### ISSUE THREAD

**Issue by ZDavid** [AntonVonGolub/Code#11]
There are no restrictions to how large the position gets, and it will hold forever until the position is profitable. 

Also Java indexing is zero based.

**Comment by jbglattfelder** [comment]
Well, actually, no, the code is not a Martingale betting system.

Let me answer from three different perspectives. The source I will refer to in the following is "The Alpha Engine: Designing an Automated Trading Algorithm" found at https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2951348 (or Chapter 3 in https://www.amazon.com/High-Performance-Computing-Finance-Solutions-Mathematics/dp/1482299666) as mentioned on our GitHub landing-page. It is the document outlining all the technical details of the trading model plus some historical context explaining the evolution of ideas.

1. Position size is not only increased but also decreased.

The positions are managed by what is called the coastline trading. Depending on the shape of the price curve, an existing position is increased or decreased. See Section 3.4 in [AlphaEngine].

However, the positions are not closed in a loss by the trading-model algorithm because, in our opinion, this should be implemented by a top-level risk-management layer. This is what is implicitly implied by the sentence:
"Finally, we have also not implemented any risk management tools." See p. 7 in [AlphaEngine].

2. Position size increases are relative.

The default size for cascading is one unit or lot. This is defined as a percentage of the current inventory. The smaller the inventory, the smaller the increment. In other words, the trading model will not run out of money. See p. 15 in [AlphaEngine].

3. There exists a difference in probabilities for observing an OS or a DC at any moment in time.

The whole notion of a Martingale betting system is anchored in the probabilities being 50%. If you read our publication:
"Now these directional changes and overshoots yield a novel context, where a cascading event is more likely to be followed by a de-cascading event than another cascading one. In detail, the probability of reaching the profitable de-cascading event after a cascade is (1−e^{-1}) ≈ 0.63, while the probability for an additional cascade is about 0.37. " See p. 7 in [AlphaEngine].


In closing, the following paragraph perhaps helps foster a better appreciation of what this code is about:
"In essence, what we present here is a proof of concept. We refrained from tweaking the model to yield better performance, in order to clearly establish and outline the model’s building blocks and fundamental behavior. We strongly believe there is great potential for obvious and straightforward improvements, which would give rise to far better models. Nevertheless, the bare-bones model we present here already has the capability of being implemented as a robust and profitable trading model that can be run in real-time." See p. 7 in [AlphaEngine].

And, yes, it is correct that Java indexing starts with zero.

**Comment by mailfilter888** [comment]
I really enjoyed reading the article. Did you have any ideas or could point me in the right direction regarding what type of top-level risk-management layer would be applicable to this this type of trading approach? I wouldn't expect traditional stop loss / trailing management would work as it would interfere with the structure of the runners. There possibly could be a global SL based on a risk/reward ratio for the account to stop a blowout but all that would do is cause the account balance to seesaw up and down in the interim. 

Thanks in advance.

**Comment by ZDavid** [comment]
Whether or not the hypothesis in the article works is irrelevant. The code
does not work as described.

Take the code to increase the long position:

double sizeToAdd = sign*size*fraction*shrinkFlong;


Doing a usage check on the size, fraction, and shrinkFlong variables shows
that  shrinkFlong  is assigned once, fraction is either 0.5 or 0.25, and
size is a function of the liquidity.

Therefore, the current total position can only scale the fraction down to
0.25, but from then on it can grow forever.

Then there is only a take profit target. No other exit.

So this strategy can have infinite position size and hold for an infinite
amount of time.

This is a joke.

**Comment by jbglattfelder** [comment]
@mailfilter888 Thanks:) Yes, a too intrusive stop loss isn't such a good idea. We recommend using our algo in a multi-currency context. This opens up many possibilities for transferring risk among problematic positions. Another approach is looking at an SL for individual buckets of USD, EUR, CHF, ..., respectively. In any case, it is tricky to delicately balance the micro-behavior with any top-level macro rules. Let us know if you have any success...

**Comment by jbglattfelder** [comment]
Dear @ZDavid 

Thank you for your interest in our work.

May I kindly remind you of the fact that no one is forcing you to use the code?

Furthermore, I recommend that you actually try and run the trading model and then add any improvements you think are necessary. I am sure that would lead to wonderful results and be so much more gratifying than any flame war you appear to want to instigate.

But that's just my humble opinion.

Have a wonderful day!

**Comment by ZDavid** [comment]
You're welcome. When you saw that you were achieving high performance on a
random walk, what steps did you take figure out why that was happening? I
understand that it can be tough to swallow that your model might be
fundamentally broken. But if you're achieving high performance on something
that has no signal by definition, then you should be very concerned.
Perhaps you should print out all the long and all the short traders
individual positions at every time step. That would be a good place to look.

On Tue, Mar 20, 2018 at 4:44 AM, James Glattfelder <notifications@github.com

**Comment by jbglattfelder** [comment]
@ZDavid Ah, how wonderful, I detect a change in tone. I was beginning to suspect that you are just an attention seeking teenager.

The proof is in the pudding. Now run along and implement the model and see for yourself, instead of wasting everyone's time.

Like, seriously!

**Comment by ZDavid** [comment]
Oh man. Alright. Best of luck to you guys.

On Tue, Mar 20, 2018 at 5:10 AM, James Glattfelder <notifications@github.com

**Comment by ZDavid** [comment]
@jbglattfelder If I may ask an honest question, in code.java, why do the for-loops on lines 867 and 935 start at 1?

**Comment by ZDavid** [comment]
![githubconversation1](https://user-images.githubusercontent.com/3291825/37658440-e847c71a-2c23-11e8-9b75-74c317135496.png)

Gotta love that infinite risk

**Comment by jbglattfelder** [comment]
@ZDavid it is very flattering to see that you are so obsessed with our project and use your precious time to anonymously try and denigrate something you don't agree with. Thank you so much.

Perhaps I was right with the attention-seeking allegation.

Btw, our actual questions are being looked into...

**Comment by ZDavid** [comment]
@jbglattfelder Don't worry, I'm just giving you a hard time because this is obviously your first java project. You'll get it some day. Just takes practice.

**Comment by ZDavid** [comment]
P.S. Please tell me you saw the word "anonymously" right below my actual name.

**Comment by jbglattfelder** [comment]
@ZDavid lol, seriously?

This is from before 3:15 pm my time:

![screen shot 2018-03-20 at 15 17 55](https://user-images.githubusercontent.com/19289440/37660210-2daa7946-2c52-11e8-9e63-385e43686caf.png)

This is from now:

![screen shot 2018-03-20 at 15 18 05](https://user-images.githubusercontent.com/19289440/37660277-537d2e5c-2c52-11e8-8dfe-97e5591d296a.png)

Please stop this laughable pettiness.

**Comment by ZDavid** [comment]
Lol You could've found me and that picture on a lot of different places.

I get that you're not very bright (otherwise you wouldn't have been involved in this total scam) so I'm trying to help you out in any way I can
