### ISSUE TITLE
in code.java, why do the for-loops on lines 867 and 935 start at 1?

### ISSUE THREAD

**Issue by ZDavid** [AntonVonGolub/Code#12]
This would mean the first open position never closes throughout the entire simulation.

**Comment by jbglattfelder** [comment]
The motivation is that we never want to decascade the initial position. It is closed when the PNL condition is satisfied.

**Comment by mailfilter888** [comment]
Do you know whether the PNL takes into account the transaction costs before reaching the target? For example, if commission was $7 plus there was swap fees of $4 would it take these into account if the profit target was $10 ie the total would need to be $21 gross profit to have a net profit for the EA target of $10?

Otherwise if a position is held onto for a long period (under the model some runners could be held onto for months or years) the swap could cause the profit to be eroded or go into negative. 
Thanks

**Comment by jbglattfelder** [comment]
So this is a toy model where the only transaction fees are the spread you pay. But yes, if you hook this up to a specific exchange that charges fees, you would need to factor that in.

Note however that in the "limit orders" version of the algo you don't pay any spread fees:
    https://github.com/AntonVonGolub/Code/tree/master/LimitOrders

**Comment by ZDavid** [comment]
No transaction costs are accounted for
