### ISSUE TITLE
Threshold when position units > 30

### ISSUE THREAD

**Issue by ko0f** [AntonVonGolub/Code#6]
In `CoastlineTrader`, when `tP > 30`, events will be taken from `runnerG[0][1]`, which was initialised as following -

    runnerG[0][1] = new Runner(0.50*deltaUp, 2.00*deltaDown, price, fxRate, 0.50*deltaUp, 0.50*deltaUp);

But notice that 50% of the threshold means that it will increase position sooner, since threshold is lower.

What is the logic in increasing the position faster when position is already large (>30)?

To my logic it should be the opposite - in order to reduce risk, threshold should be higher the bigger our position is.

**Comment by VladUZH** [comment]
Dear ko0f, the coastline trader in your example is a Long one, so he increases position buying (using deltaDown) and decreases it selling some volume (using deltaUp). DeltaUp of the runnerG[0][1] is 4 times lower than its deltaDown, so the agent should 4 time more often decrease the position rather than increase it.

**Comment by ko0f** [comment]
Right. Thanks!
